package asembly.exception;

public enum StatusCodeException {
    USER_NOT_FOUND,
    USER_ALREADY_EXIST,
    CHAT_NOT_FOUND,
    MESSAGE_NOT_FOUND,
    USER_CREATION_FAILED,
    CHAT_CREATION_FAILED,
    MESSAGE_CREATION_FAILED,
    PASSWORD_NOT_REQUIRED,
    UNAUTHORIZED_SERVICE
}
